### ISSUE TITLE
Error opening stream

### ISSUE THREAD

**Issue by miguelaferreira** [lamelas/rtp-plex-plugin#1]
Thanks for the plugin! I'm trying to get it running.

First I had to install python yaml in the plex bundle and after that I could see the plugin being loaded.
Now I'm facing another issue with playing a stream.

This is the log output:

```
11:35:49.232517: com.plexapp.plugins.rtp                 :   (Framework) Handling request :  /video/rtp/:/function/ListEpisodes
11:35:49.232794: com.plexapp.plugins.rtp                 :   ListEpisodes
11:35:49.232888: com.plexapp.plugins.rtp                 :   (Framework) Calling named function 'ListEpisodes'
11:35:49.232941: com.plexapp.plugins.rtp                 :   (RTP) Getting episodes for show (tvprog = 23768)
11:35:50.926419: com.plexapp.plugins.rtp                 :   (Framework) HTTPError when requesting 'http://ww1.rtp.pt/multimedia/progVideo.php?tvprog=23768'
11:35:50.929512: com.plexapp.plugins.rtp                 :   (Framework) An exception happened:
Traceback (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-24ffd60/Framework.bundle/Contents/Resources/Versions/1/Python/PMS/Plugin.py", line 712, in __call
    return function(*args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/RTP.bundle/Contents/Code/__init__.py", line 231, in ListEpisodes
    sopa = BeautifulSoup(data)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/RTP.bundle/Contents/Code/BeautifulSoup.py", line 1517, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/RTP.bundle/Contents/Code/BeautifulSoup.py", line 1142, in __init__
    self._feed(isHTML=isHTML)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/RTP.bundle/Contents/Code/BeautifulSoup.py", line 1166, in _feed
    smartQuotesTo=self.smartQuotesTo, isHTML=isHTML)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/RTP.bundle/Contents/Code/BeautifulSoup.py", line 1768, in __init__
    self._detectEncoding(markup, isHTML)
  File "/config/Library/Application Support/Plex Media Server/Plug-ins/RTP.bundle/Contents/Code/BeautifulSoup.py", line 1913, in _detectEncoding
    '^<\?.*encoding=[\'"](.*?)[\'"].*\?>').match(xml_data)
TypeError: expected string or buffer
```

Any clue what it might be?

**Comment by lamelas** [comment]
Olá Miguel!

Este plugin está mais ou menos abandonado há uns anos. Se quiseres submeter um pull request para corrigir isto terei todo o gosto em aceitar. :)

**Comment by miguelaferreira** [comment]
Ja andei a ver se percebia o esquema no site da RTP, mas estava difícil.
Depois fui ver como fazem no plugin do kodi e acho que entendi como funciona.
Quando tiver tempo vou tentar implementar e depois abro um PR.
